### ISSUE TITLE
Uncaught Error: EACCES, permission denied

### ISSUE THREAD

**Issue by Aldarone** [v3ss0n/goto#17]
If there is a file with no read permission or a directory with no execute permission in the project, `goto:project-symbol` fails with this error :

```
Uncaught Error: EACCES, permission denied '/removed/for/privacy/.Trash-3008' fs.js:691
```

**Comment by acusti** [comment]
Switched over to using the `traverseTreeSync` method from atom/fs-plus as of 1.8.0, which I’m hoping will avoid this error.
