### ISSUE TITLE
I will take over this project.

### ISSUE THREAD

**Issue by v3ss0n** [v3ss0n/goto#50]
This is very useful and sad to see it go , can i take over?

**Comment by mkleehammer** [comment]
I'll transfer the repo to you now...

**Comment by mkleehammer** [comment]
I knew that was going to happen: "v3ss0n/goto already exists" 

Can you delete your github repo?

**Comment by v3ss0n** [comment]
Ok i will delete it  first

**Comment by v3ss0n** [comment]
You can transfer now , deleted.

**Comment by v3ss0n** [comment]
Deleted now you can transfer.

**Comment by acusti** [comment]
@v3ss0n Happy to see someone take over the goto package! Will you accept PRs that remove/update calls to deprecated Atom APIs? Should I hold off and let you make the changes?

**Comment by v3ss0n** [comment]
Thanks alot @acusti  i will gladly accept PRs and also issues  !

**Comment by magalhas** [comment]
Nice. So what's the status on removing those deprecated calls? This is the only ugly duck in my atom as of now :)

**Comment by acusti** [comment]
@magalhas See #51
