### ISSUE TITLE
Goto declaration doesn't work

### ISSUE THREAD

**Issue by matthieuheitz** [v3ss0n/goto#84]
I installed this plugin, I see the list of symbols when doing Goto File Symbol or Goto Project Symbol, but Goto Declaration doesn't work.
It doesn't work from the right click menu, nor from the Packages menu, nor with the shortcut.
Is there a debian package that I should install for it to work ?

I'm on Ubuntu 14.04, I use Atom 1.5.4 and version 1.7.1 of goto

**Comment by GabeIsman** [comment]
Doesn't work for me either on OS X, Atom 1.5.3, goto 1.7.1.

**Comment by brunolemos** [comment]
It freezes my atom (mac).

**Comment by rodrigo-martinezd** [comment]
In Fedora 23 it freezes my atom

**Comment by mjmathew** [comment]
Same here, totally crashes atom

**Comment by ChristopherFunk** [comment]
Freezes and Crashes my Atom on Windows 8.1, Atom 1.7.4

**Comment by danielterega** [comment]
Uncaught Error: ENOENT: no such file or directory

**Atom Version**: 1.8.0
**System**: Mac OS X 10.10.2
**Thrown From**: [goto](https://github.com/v3ss0n/goto) package, v1.7.1

**Comment by acusti** [comment]
Should be fixed by 1.8.0
