### ISSUE TITLE
Not working: goto declaration will cause atom dead.

### ISSUE THREAD

**Issue by fleksin** [v3ss0n/goto#96]
Not working on my Mac, the system OS X 10.11.6. Using go declaration function will cause serious dead of the computer. So...

**Comment by gingi** [comment]
+1

**Comment by bashbug** [comment]
same here Fedora 24

**Comment by arleslie** [comment]
Causes atom to lockup for me. Mac OS X 10.11.6 (15G31)

**Comment by bobbyvinas** [comment]
+1 macOS Sierra 10.12 (16A323)

**Comment by Janjuks** [comment]
Happens also on Win 10. 
goto version: 1.7.1
atom: 1.11.2
language: Elm

**Comment by henrebotha** [comment]
+1.

macOS Sierra 10.12 16A323

Atom 1.11.2

**Comment by fischeversenker** [comment]
same here:
Win10
Atom 1.11.2
goto 1.7.1
JavaScript

**Comment by StanBright** [comment]
I have the same problem receiving the notice: "Project has no tags file or it is empty".

**Comment by GinjiBan** [comment]
+1 macOS Sierra 10.12

**Comment by acusti** [comment]
Just published 1.8.0 which I’m hopeful resolves this issue. Please update if that isn’t the case.
